name: Deploy to Strato

# Dieser Workflow startet, wenn ein Commit in den "main" Branch gepusht wird
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Schritt 1: Checke das Repository in den GitHub Runner aus
    - name: Checkout repository
      uses: actions/checkout@v2

    # Schritt 2: Verbinde dich via FTP und lade die Dateien hoch
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}   # FTP-Server von Strato
        username: ${{ secrets.FTP_USERNAME }}  # FTP-Benutzername
        password: ${{ secrets.FTP_PASSWORD }}  # FTP-Passwort
        local-dir: ./  # Das Verzeichnis, das hochgeladen werden soll, normalerweise der Root des Repositories
        server-dir: ${{ secrets.FTP_PATH }}  # Zielverzeichnis auf dem FTP-Server, normalerweise /htdocs
        
